/** Safety and Compliance page and Cookie Policy, one document per language. The safety page describes how Nekaf's voice agents
 *  are kept inside the workshop's own rules; the cookie policy matches what the site actually sets (see components/Consent.tsx). */
import type { LegalDoc } from "./legal";

export const SAFETY: Record<string, LegalDoc> = {
  en: {
    title: "Safety and Compliance",
    updated: "Last updated: 25 September 2026",
    description: "Nekaf is built for accountability in the workshop: full audit trails, escalation rules approved by your workshop manager, GDPR compliant data handling, controls aligned with SOC 1 and ISO 27001, and human oversight by design.",
    intro: "Nekaf is workflow automation for automotive service businesses: independent garages, dealerships, body and paint shops and tire centers. It answers calls, books and moves service appointments, gives car-ready status and routes breakdowns and warning-light calls by the workshop's own rules. It gives no repair diagnosis over the phone, never approves warranty or goodwill decisions and never overrides the workshop's judgment. Every rule, every decision and every escalation is documented and auditable. This page describes how safety, data protection and governance are built in.",
    sections: [
      { id: "scope", title: "1. Scope statement", paragraphs: ["Nekaf handles administrative customer contacts: booking, rescheduling, car-ready status, reminders, follow-up and quotes read from the workshop's own price list. It gives no repair diagnosis and never tells a driver what is wrong with their car. When a caller describes a breakdown, a fault or a warning light, the agent applies the workshop's own rules to decide how urgently the car needs to be seen and by whom, and it hands over to a service advisor or mechanic whenever the rules or the caller ask for it."] },
      { id: "escalation", title: "2. Escalation principles", paragraphs: ["Breakdowns, undriveable cars, safety-related warning lights and upset customers go to a person, with the transcript and a short summary. When the agent is uncertain, it routes to a human rather than guessing. Safety comes before automation, always."], items: ["Escalation rules are defined and approved by the workshop manager.", "Urgent cases are transferred live during opening hours. Outside opening hours the agent takes a message or forwards the call to the on-duty number the workshop has set.", "Callers can reach a person at any point by asking for one."] },
      { id: "audit", title: "3. Complete audit trail", paragraphs: ["Every decision the agent takes is logged. Each call has a full transcript with structured data: reason for calling, vehicle and appointment details where given, actions taken, outcome and any escalation. Rules are versioned, so the workshop can see which rules applied to any call at any time."] },
      { id: "oversight", title: "4. Human oversight", paragraphs: ["Flagged calls land in a review queue in the console. Rules go live only after the workshop has approved them, and edge cases are handled by people, not by the agent."] },
      { id: "data", title: "5. Data handling and security", paragraphs: ["Security for all customer and vehicle data, with encryption, access controls and compliance built in."], items: ["Encryption in transit and at rest.", "Role-based access with audit logging.", "Configurable retention policies per customer, so each workshop decides how long calls, recordings and transcripts are kept.", "GDPR compliant processing for workshops in the EU, with a data processing agreement.", "Processing in line with US state privacy laws for workshops in the United States.", "Controls aligned with SOC 1 and ISO 27001, and readiness for the EU AI Act.", "Data residency in the EU or the US, at the customer's choice.", "Call recordings and transcripts are stored only for the agreed retention period and are then deleted or returned."] },
      { id: "transparency", title: "6. Transparency by default", paragraphs: ["Drivers always know what they are talking to."], items: ["Callers are told they are speaking with an AI assistant.", "Hand-offs to the workshop's staff are announced clearly.", "Full transcripts are available to the workshop, and to drivers on request through the workshop."] },
      { id: "governance", title: "7. Governance", paragraphs: ["We work with the workshop manager to design rules that fit the way the workshop works and the standards it sets."], items: ["Rules are co-designed with the workshop manager.", "All routing and escalation rules are reviewed and approved before deployment.", "Rules are audited and updated regularly.", "Escalation chains are documented and known to the team."] },
      { id: "contact", title: "8. Questions about compliance", paragraphs: ["Our team is happy to discuss your requirements and to share our security and compliance one-pager for your procurement or IT team. Write to legal@nekaf.ai or book a demo."] },
    ],
  },
  nl: {
    title: "Veiligheid en compliance",
    updated: "Laatst bijgewerkt: 25 september 2026",
    description: "Nekaf is gebouwd voor verantwoording in de werkplaats: volledige audittrails, escalatieregels goedgekeurd door uw werkplaatschef, AVG-conforme gegevensverwerking, maatregelen in lijn met SOC 1 en ISO 27001, en menselijk toezicht by design.",
    intro: "Nekaf is workflowautomatisering voor autobedrijven: onafhankelijke garages, dealers, schadeherstelbedrijven en bandenspecialisten. Het beantwoordt gesprekken, plant en verzet werkplaatsafspraken, geeft door wanneer de auto klaar is en routeert meldingen van pech en waarschuwingslampjes volgens de eigen regels van de werkplaats. Het stelt geen diagnose aan de telefoon, keurt nooit garantie- of coulancebeslissingen goed en gaat nooit boven het oordeel van de werkplaats. Elke regel, elke beslissing en elke escalatie is gedocumenteerd en controleerbaar. Deze pagina beschrijft hoe veiligheid, gegevensbescherming en governance zijn ingebouwd.",
    sections: [
      { id: "scope", title: "1. Reikwijdte", paragraphs: ["Nekaf handelt administratieve klantcontacten af: afspraken maken en verzetten, de status van de auto, herinneringen, opvolging en prijsopgaven op basis van de eigen prijslijst van de werkplaats. Het stelt geen diagnose op afstand en vertelt een bestuurder nooit wat er aan de auto mankeert. Beschrijft een beller pech, een storing of een brandend waarschuwingslampje, dan past de agent de eigen regels van de werkplaats toe om te bepalen hoe snel de auto gezien moet worden en door wie, en draagt over aan een serviceadviseur of monteur zodra de regels of de beller daarom vragen."] },
      { id: "escalation", title: "2. Escalatieprincipes", paragraphs: ["Pech, auto's die niet meer kunnen rijden, veiligheidsgerelateerde waarschuwingslampjes en ontevreden klanten gaan naar een medewerker, met transcript en korte samenvatting. Bij twijfel schakelt de agent een mens in in plaats van te gokken. Veiligheid gaat altijd vóór automatisering."], items: ["Escalatieregels worden vastgesteld en goedgekeurd door de werkplaatschef.", "Urgente gevallen worden tijdens openingstijden live doorverbonden. Buiten openingstijden neemt de agent een bericht aan of verbindt door naar het nummer van de dienstdoende medewerker dat de werkplaats heeft ingesteld.", "Bellers kunnen op elk moment een medewerker bereiken door daarom te vragen."] },
      { id: "audit", title: "3. Volledige audittrail", paragraphs: ["Elke beslissing van de agent wordt gelogd. Elk gesprek heeft een volledig transcript met gestructureerde gegevens: reden van bellen, voertuig- en afspraakgegevens voor zover opgegeven, ondernomen acties, uitkomst en eventuele escalatie. Regels zijn geversioneerd, zodat de werkplaats altijd kan zien welke regels bij welk gesprek golden."] },
      { id: "oversight", title: "4. Menselijk toezicht", paragraphs: ["Gemarkeerde gesprekken komen in een beoordelingswachtrij in de console. Regels gaan pas live nadat de werkplaats ze heeft goedgekeurd, en uitzonderingen worden door mensen afgehandeld, niet door de agent."] },
      { id: "data", title: "5. Gegevensverwerking en beveiliging", paragraphs: ["Beveiliging voor alle klant- en voertuiggegevens, met versleuteling, toegangsbeheer en compliance ingebouwd."], items: ["Versleuteling onderweg en in rust.", "Rolgebaseerde toegang met auditlogging.", "Instelbaar bewaarbeleid per klant, zodat elke werkplaats zelf bepaalt hoe lang gesprekken, opnames en transcripten worden bewaard.", "AVG-conforme verwerking voor werkplaatsen in de EU, met een verwerkersovereenkomst.", "Verwerking in lijn met de privacywetten van de Amerikaanse staten voor werkplaatsen in de Verenigde Staten.", "Maatregelen in lijn met SOC 1 en ISO 27001, en voorbereid op de EU AI Act.", "Gegevensopslag in de EU of in de VS, naar keuze van de klant.", "Gespreksopnames en transcripten worden alleen gedurende de afgesproken bewaartermijn bewaard en daarna verwijderd of teruggegeven."] },
      { id: "transparency", title: "6. Transparantie als standaard", paragraphs: ["Bestuurders weten altijd met wie of wat ze spreken."], items: ["Bellers horen dat ze met een AI-assistent spreken.", "Overdrachten naar medewerkers van de werkplaats worden duidelijk aangekondigd.", "Volledige transcripten zijn beschikbaar voor de werkplaats, en op verzoek via de werkplaats voor bestuurders."] },
      { id: "governance", title: "7. Governance", paragraphs: ["We werken samen met de werkplaatschef aan regels die passen bij de manier waarop de werkplaats werkt en bij de normen die zij stelt."], items: ["Regels worden samen met de werkplaatschef ontworpen.", "Alle routerings- en escalatieregels worden vóór livegang beoordeeld en goedgekeurd.", "Regels worden regelmatig geaudit en bijgewerkt.", "Escalatieketens zijn gedocumenteerd en bekend bij het team."] },
      { id: "contact", title: "8. Vragen over compliance", paragraphs: ["Ons team bespreekt graag uw eisen en deelt onze onepager over beveiliging en compliance voor uw inkoop- of IT-team. Mail naar legal@nekaf.ai of vraag een demo aan."] },
    ],
  },
  de: {
    title: "Sicherheit und Compliance",
    updated: "Zuletzt aktualisiert: 25. September 2026",
    description: "Nekaf ist für Verantwortlichkeit in der Werkstatt gebaut: vollständige Audit-Trails, vom Werkstattleiter freigegebene Eskalationsregeln, DSGVO-konforme Datenverarbeitung, Kontrollen im Einklang mit SOC 1 und ISO 27001 und menschliche Aufsicht by Design.",
    intro: "Nekaf ist Workflow-Automatisierung für Kfz-Servicebetriebe: freie Werkstätten, Autohäuser, Karosserie- und Lackierbetriebe und Reifenservices. Es beantwortet Anrufe, bucht und verschiebt Werkstatttermine, gibt Auskunft, ob das Fahrzeug abholbereit ist, und leitet Anrufe zu Pannen und Warnleuchten nach den eigenen Regeln der Werkstatt weiter. Es stellt am Telefon keine Reparaturdiagnose, genehmigt nie Garantie- oder Kulanzentscheidungen und stellt sich nie über das Urteil der Werkstatt. Jede Regel, jede Entscheidung und jede Eskalation ist dokumentiert und prüfbar. Diese Seite beschreibt, wie Sicherheit, Datenschutz und Governance eingebaut sind.",
    sections: [
      { id: "scope", title: "1. Geltungsbereich", paragraphs: ["Nekaf übernimmt administrative Kundenkontakte: Terminbuchung und Terminverschiebung, Fahrzeugstatus, Erinnerungen, Nachfassen und Preisauskünfte aus der eigenen Preisliste der Werkstatt. Es stellt keine Ferndiagnose und sagt einem Fahrer nie, was an seinem Fahrzeug defekt ist. Schildert ein Anrufer eine Panne, eine Störung oder eine leuchtende Warnleuchte, wendet der Agent die eigenen Regeln der Werkstatt an, um zu bestimmen, wie dringend und von wem das Fahrzeug gesehen werden muss, und übergibt an einen Serviceberater oder Mechaniker, sobald die Regeln oder der Anrufer es verlangen."] },
      { id: "escalation", title: "2. Eskalationsprinzipien", paragraphs: ["Pannen, nicht mehr fahrbereite Fahrzeuge, sicherheitsrelevante Warnleuchten und verärgerte Kunden gehen an eine Person, mit Transkript und kurzer Zusammenfassung. Ist der Agent unsicher, leitet er an einen Menschen weiter, statt zu raten. Sicherheit geht immer vor Automatisierung."], items: ["Eskalationsregeln werden vom Werkstattleiter festgelegt und freigegeben.", "Dringende Fälle werden zu Öffnungszeiten live durchgestellt. Außerhalb der Öffnungszeiten nimmt der Agent eine Nachricht auf oder leitet an die von der Werkstatt hinterlegte Bereitschaftsnummer weiter.", "Anrufer erreichen jederzeit eine Person, wenn sie danach fragen."] },
      { id: "audit", title: "3. Vollständiger Audit-Trail", paragraphs: ["Jede Entscheidung des Agenten wird protokolliert. Jeder Anruf hat ein vollständiges Transkript mit strukturierten Daten: Anrufgrund, Fahrzeug- und Termindaten soweit angegeben, ergriffene Maßnahmen, Ergebnis und etwaige Eskalation. Regeln sind versioniert, sodass die Werkstatt jederzeit sehen kann, welche Regeln bei welchem Anruf galten."] },
      { id: "oversight", title: "4. Menschliche Aufsicht", paragraphs: ["Markierte Anrufe landen in einer Prüfwarteschlange in der Konsole. Regeln gehen erst live, wenn die Werkstatt sie freigegeben hat, und Sonderfälle bearbeiten Menschen, nicht der Agent."] },
      { id: "data", title: "5. Datenverarbeitung und Sicherheit", paragraphs: ["Sicherheit für alle Kunden- und Fahrzeugdaten, mit Verschlüsselung, Zugriffskontrollen und eingebauter Compliance."], items: ["Verschlüsselung bei Übertragung und Speicherung.", "Rollenbasierter Zugriff mit Audit-Protokollierung.", "Konfigurierbare Aufbewahrungsregeln je Kunde, sodass jede Werkstatt selbst bestimmt, wie lange Anrufe, Aufzeichnungen und Transkripte aufbewahrt werden.", "DSGVO-konforme Verarbeitung für Werkstätten in der EU, mit Auftragsverarbeitungsvertrag.", "Verarbeitung im Einklang mit den Datenschutzgesetzen der US-Bundesstaaten für Werkstätten in den Vereinigten Staaten.", "Kontrollen im Einklang mit SOC 1 und ISO 27001 sowie Vorbereitung auf den EU AI Act.", "Datenspeicherung in der EU oder in den USA, nach Wahl des Kunden.", "Gesprächsaufzeichnungen und Transkripte werden nur für die vereinbarte Aufbewahrungsfrist gespeichert und danach gelöscht oder zurückgegeben."] },
      { id: "transparency", title: "6. Transparenz als Standard", paragraphs: ["Fahrer wissen immer, mit wem oder was sie sprechen."], items: ["Anrufer erfahren, dass sie mit einem KI-Assistenten sprechen.", "Übergaben an Mitarbeitende der Werkstatt werden klar angekündigt.", "Vollständige Transkripte stehen der Werkstatt zur Verfügung, und Fahrern auf Anfrage über die Werkstatt."] },
      { id: "governance", title: "7. Governance", paragraphs: ["Wir arbeiten mit dem Werkstattleiter an Regeln, die zur Arbeitsweise der Werkstatt und zu ihren Standards passen."], items: ["Regeln werden gemeinsam mit dem Werkstattleiter entworfen.", "Alle Weiterleitungs- und Eskalationsregeln werden vor dem Livegang geprüft und freigegeben.", "Regeln werden regelmäßig auditiert und aktualisiert.", "Eskalationsketten sind dokumentiert und dem Team bekannt."] },
      { id: "contact", title: "8. Fragen zur Compliance", paragraphs: ["Unser Team bespricht gern Ihre Anforderungen und teilt unseren Sicherheits- und Compliance-Einseiter für Ihren Einkauf oder Ihre IT. Schreiben Sie an legal@nekaf.ai oder buchen Sie eine Demo."] },
    ],
  },
};

export const COOKIES: Record<string, LegalDoc> = {
  en: {
    title: "Cookie Policy",
    updated: "Last updated: 25 September 2026",
    description: "How nekaf.ai uses cookies and similar technologies, what is set only with your consent, and how to change your choice.",
    intro: "This policy explains which cookies and similar technologies nekaf.ai uses, why, and how you can control them. It complements our Privacy Policy.",
    sections: [
      { id: "what", title: "1. What cookies are", paragraphs: ["Cookies are small text files that a website stores on your device. Similar technologies, such as browser storage, work in the same way. They can keep a setting between visits, recognise a returning browser or help us understand how the site is used."] },
      { id: "use", title: "2. What we set and why", paragraphs: ["We keep the site as light as possible. Nothing is set for analytics until you have said yes in the banner."], items: ["Your consent choice: one entry in your browser's local storage that remembers whether you accepted or declined analytics, so we do not ask again on every visit. It contains no personal data.", "Analytics (only after consent): PostHog, hosted in the EU, records page views and clicks so we can see which pages help visitors and which do not. It sets cookies with the prefix ph_ that identify a browser, not a person.", "Booking: when you open the demo calendar, Cal.com may set its own functional cookies for the booking flow. These are governed by Cal.com's policy."] },
      { id: "no", title: "3. What we do not do", paragraphs: ["We set no advertising or marketing cookies, and we do not sell or share visitor data with advertisers."] },
      { id: "manage", title: "4. Managing your choice", paragraphs: ["You can accept or decline analytics in the banner on your first visit. To change your choice later, clear the site's data in your browser and the banner will appear again, or block cookies for nekaf.ai in your browser settings. Declining analytics does not limit the site in any way."] },
      { id: "contact", title: "5. Contact", paragraphs: ["Questions about this policy: privacy@nekaf.ai."] },
    ],
  },
  nl: {
    title: "Cookiebeleid",
    updated: "Laatst bijgewerkt: 25 september 2026",
    description: "Hoe nekaf.ai cookies en vergelijkbare technieken gebruikt, wat alleen met uw toestemming wordt geplaatst en hoe u uw keuze aanpast.",
    intro: "Dit beleid legt uit welke cookies en vergelijkbare technieken nekaf.ai gebruikt, waarom, en hoe u ze beheert. Het is een aanvulling op ons privacybeleid.",
    sections: [
      { id: "what", title: "1. Wat cookies zijn", paragraphs: ["Cookies zijn kleine tekstbestanden die een website op uw apparaat opslaat. Vergelijkbare technieken, zoals browseropslag, werken op dezelfde manier. Ze kunnen een instelling bewaren tussen bezoeken, een terugkerende browser herkennen of ons helpen te begrijpen hoe de site wordt gebruikt."] },
      { id: "use", title: "2. Wat we plaatsen en waarom", paragraphs: ["We houden de site zo licht mogelijk. Voor analyse wordt niets geplaatst totdat u in de banner ja hebt gezegd."], items: ["Uw toestemmingskeuze: één vermelding in de lokale opslag van uw browser die onthoudt of u analyse hebt geaccepteerd of geweigerd, zodat we het niet bij elk bezoek opnieuw vragen. Deze bevat geen persoonsgegevens.", "Analyse (alleen na toestemming): PostHog, gehost in de EU, registreert paginaweergaven en klikken zodat we zien welke pagina's bezoekers helpen en welke niet. Het plaatst cookies met het voorvoegsel ph_ die een browser identificeren, geen persoon.", "Afspraken: als u de demokalender opent, kan Cal.com eigen functionele cookies plaatsen voor het boekingsproces. Daarvoor geldt het beleid van Cal.com."] },
      { id: "no", title: "3. Wat we niet doen", paragraphs: ["We plaatsen geen advertentie- of marketingcookies en we verkopen of delen geen bezoekersgegevens met adverteerders."] },
      { id: "manage", title: "4. Uw keuze beheren", paragraphs: ["Bij uw eerste bezoek kunt u analyse in de banner accepteren of weigeren. Wilt u uw keuze later wijzigen, wis dan de sitegegevens in uw browser; de banner verschijnt dan opnieuw. U kunt cookies voor nekaf.ai ook blokkeren in uw browserinstellingen. Weigeren beperkt de site op geen enkele manier."] },
      { id: "contact", title: "5. Contact", paragraphs: ["Vragen over dit beleid: privacy@nekaf.ai."] },
    ],
  },
  de: {
    title: "Cookie-Richtlinie",
    updated: "Zuletzt aktualisiert: 25. September 2026",
    description: "Wie nekaf.ai Cookies und ähnliche Technologien nutzt, was nur mit Ihrer Einwilligung gesetzt wird und wie Sie Ihre Wahl ändern.",
    intro: "Diese Richtlinie erklärt, welche Cookies und ähnlichen Technologien nekaf.ai nutzt, warum, und wie Sie sie steuern können. Sie ergänzt unsere Datenschutzerklärung.",
    sections: [
      { id: "what", title: "1. Was Cookies sind", paragraphs: ["Cookies sind kleine Textdateien, die eine Website auf Ihrem Gerät speichert. Ähnliche Technologien wie der Browserspeicher funktionieren genauso. Sie können eine Einstellung zwischen Besuchen bewahren, einen wiederkehrenden Browser erkennen oder uns helfen zu verstehen, wie die Seite genutzt wird."] },
      { id: "use", title: "2. Was wir setzen und warum", paragraphs: ["Wir halten die Seite so leicht wie möglich. Für Analysen wird nichts gesetzt, bevor Sie im Banner zugestimmt haben."], items: ["Ihre Einwilligungswahl: ein Eintrag im lokalen Speicher Ihres Browsers, der festhält, ob Sie Analysen akzeptiert oder abgelehnt haben, damit wir nicht bei jedem Besuch erneut fragen. Er enthält keine personenbezogenen Daten.", "Analysen (nur nach Einwilligung): PostHog, in der EU gehostet, erfasst Seitenaufrufe und Klicks, damit wir sehen, welche Seiten Besuchern helfen und welche nicht. Es setzt Cookies mit dem Präfix ph_, die einen Browser identifizieren, keine Person.", "Terminbuchung: Wenn Sie den Demo-Kalender öffnen, kann Cal.com eigene funktionale Cookies für den Buchungsablauf setzen. Dafür gilt die Richtlinie von Cal.com."] },
      { id: "no", title: "3. Was wir nicht tun", paragraphs: ["Wir setzen keine Werbe- oder Marketing-Cookies und verkaufen oder teilen keine Besucherdaten mit Werbetreibenden."] },
      { id: "manage", title: "4. Ihre Wahl verwalten", paragraphs: ["Beim ersten Besuch können Sie Analysen im Banner akzeptieren oder ablehnen. Um Ihre Wahl später zu ändern, löschen Sie die Website-Daten in Ihrem Browser; der Banner erscheint dann erneut. Sie können Cookies für nekaf.ai auch in den Browsereinstellungen blockieren. Ablehnen schränkt die Seite in keiner Weise ein."] },
      { id: "contact", title: "5. Kontakt", paragraphs: ["Fragen zu dieser Richtlinie: privacy@nekaf.ai."] },
    ],
  },
};
